lib/estimator/web/router.ex
defmodule Estimator.Web.Router do
  use Estimator.Web, :router
  alias Estimator.Web.CspHeader

  require Ueberauth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug CspHeader
  end

  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
#    plug Guardian.Plug.LoadResource
    plug Guardian.Plug.EnsureAuthenticated, handler: Estimator.Web.PageController
  end

  forward "/graphiql", Absinthe.Plug.GraphiQL, schema: Estimator.GraphQL.Schema

  scope "/login", Estimator.Web do
    pipe_through [:browser]

    get "/", PageController, :login
  end

  scope "/", Estimator.Web do
    pipe_through [:browser, :browser_auth]

    get "/", PageController, :index

    scope "/board/:board_id" do
      get "/backlog", PageController, :backlog
      get "/backlog/refresh", PageController, :backlog_refresh
      get "/estimate", PageController, :estimate
      get "/estimated", PageController, :estimated
      get "/issues/:issue_key/deselect", PageController, :deselect_issue
      get "/issues/deselect_all", PageController, :deselect_all_issues
      post "/issues/select", PageController, :select_issues
    end
  end

  scope "/auth", Estimator.Web do
      pipe_through [:browser]

      get "/:identity", AuthController, :login
      get "/:identity/callback", AuthController, :callback
      post "/:identity/callback", AuthController, :callback
      delete "/logout", AuthController, :delete
  end
end

lib/estimator/web/controllers/auth_controller.ex
defmodule Estimator.Web.AuthController do
  use Estimator.Web, :controller
  plug Ueberauth

  alias Estimator.User.UserFromAuth
  import Guardian.Plug, only: [sign_out: 1, sign_in: 2]

  def delete(conn, _params) do
    conn
    |> sign_out
    |> put_flash(:info, "You have been logged out!")
    |> configure_session(drop: true)
    |> redirect(to: "/login")
  end

  def callback(%{assigns: %{ueberauth_failure: _fails}} = conn, _params) do
    conn
    |> put_flash(:error, "Failed to authenticate.")
    |> redirect(to: "/login")
  end

  def callback(%{assigns: %{ueberauth_auth: auth}} = conn, _params) do
    case UserFromAuth.find_or_create(auth) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "Successfully authenticated.")
        |> sign_in(user)
        |> put_session(:current_user, user)
        |> redirect(to: "/")
      {:error, reason} ->
        conn
        |> put_flash(:error, reason)
        |> redirect(to: "/")
    end
  end

end

lib/estimator/web/controllers/page_controller.ex
defmodule Estimator.Web.PageController do
  use Estimator.Web, :controller

  alias Estimator.Api.Jira
  alias Estimator.Board
  alias Estimator.Issue
  alias Estimator.Issue.SelectedIssue

  plug Ueberauth

  def login(conn, _params) do
    render conn, current_user: false
  end

  def index(conn, _params) do
    redirect(conn, to: page_path(conn, :backlog, board_id(conn)))
  end

  def backlog(conn, %{"board_id" => board_id}) do
    backlog = board_id
      |> Jira.backlog
      |> Jira.backlog_filter(Issue.list_selected(board_id))
      |> Jira.backlog_filter_estimated

    template(conn, board_id, backlog: backlog)
  end

  def backlog_refresh(conn, %{"board_id" => board_id}) do
    Jira.invalidate_backlog(board_id)

    conn
      |> put_flash(:success, "Updated issues from Jira")
      |> redirect(to: page_path(conn, :backlog, board_id))
  end

  def estimate(conn, %{"board_id" => board_id}) do
    template(conn, board_id, selected_issues: Issue.list_to_estimate(board_id))
  end

  def estimated(conn, %{"board_id" => board_id}) do
    template(conn, board_id, issues: Issue.list_estimated(board_id))
  end

  def select_issues(conn, %{"selected_issue" => issues, "board_id" => board_id}) do
    selected_issues = for {issue, selected} <- issues, selected == "true", do: issue
    Issue.import_issues_from_jira(board_id, selected_issues)

    success(conn, "Issue selected", page_path(conn, :estimate, board_id))
  end

  def deselect_issue(conn, %{"issue_key" => issue_key, "board_id" => board_id}) do
    Issue.deselect(issue_key)

    success(conn, "Issue deselected", page_path(conn, :estimate, board_id))
  end

  def deselect_all_issues(conn, %{"board_id" => board_id}) do
    Issue.deselect_all(board_id)

    success(conn, "All issues deselected", page_path(conn, :estimate, board_id))
  end

  def unauthenticated(conn, _) do
    redirect(conn, to: "/login")
  end

 # ---

 defp template(conn, board_id, assigns) do
    render conn, Keyword.merge(assigns, [
        current_user: get_session(conn, :current_user),
        changeset: SelectedIssue.changeset(%SelectedIssue{}),
        board_id: board_id
      ])
 end

  defp board_id(conn) do
    user = get_session(conn, :current_user)

    Board.last_used_board_id(user.id) || Application.get_env(:jira, :board_id, System.get_env("JIRA_BOARD_ID"))
  end

  defp success(conn, message, redirect_path) do
    msg(conn, :success, message, redirect_path)
  end

  defp msg(conn, type, message, redirect_path) do
      conn
      |> put_flash(type, message)
      |> redirect(to: redirect_path)
    end
end

lib/estimator/web/views/error_view.ex
defmodule Estimator.Web.ErrorView do
  use Estimator.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

lib/estimator/web/views/jira_view.ex
defmodule Estimator.Web.JiraView do
  use Estimator.Web, :view
end

lib/estimator/web/views/layout_view.ex
defmodule Estimator.Web.LayoutView do
  use Estimator.Web, :view

  def partial(template, assigns \\ %{}) do
    render(Estimator.Web.PartialView, template, assigns)
  end
end

lib/estimator/web/views/page_view.ex
defmodule Estimator.Web.PageView do
  use Estimator.Web, :view

  def partial(template, assigns \\ %{}) do
    render(Estimator.Web.PartialView, template, assigns)
  end

  def estimation_field do
    Estimator.Api.Jira.estimation_field()
  end

  def estimation_to_card(estimation) do
    Estimator.Vote.Card.to_card(estimation)
  end

  def issue_json(issue) do
    Poison.encode!(%{
      key: issue.key,
      summary: issue.summary,
      link: issue.link,
      description: issue.description,
      attachments: Enum.map(issue["fields"]["attachment"] || [], &(&1["content"])),
      type: %{
        iconUrl: issue["fields"]["issuetype"]["iconUrl"],
        name: issue["fields"]["issuetype"]["name"],
      },
    })
  end
end

lib/estimator/web/views/partial_view.ex
defmodule Estimator.Web.PartialView do
  use Estimator.Web, :view

  def jira_link(issue) do
    Estimator.Issue.IssueFromJira.link(issue)
  end
end

lib/estimator/web/views/vote_view.ex
defmodule Estimator.Web.VoteView do
  use Estimator.Web, :view

  def render("vote.json", vote) do
    %{
      issue_key: vote.issue_key,
      user_id: vote.user_id,
      vote: vote.vote,
      timestamp: :os.system_time(:milli_seconds),
    }
  end
end

lib/estimator/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <%= if Guardian.Plug.current_token(@conn) do %>
      <meta name='guardian_token' content="<%= Guardian.Plug.current_token(@conn) %>">
    <% end %>

    <title>Estimator</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">

    <!--     Fonts and icons     -->
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='//fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300' rel='stylesheet' type='text/css'>
  </head>

  <body>
    <header class="header">
      <%= partial "navigation.html", assigns %>
    </header>

    <section class="section section-nude">
      <div class="container">
        <%= if get_flash(@conn, :success) do %>
          <p class="alert alert-success" role="alert"><%= get_flash(@conn, :success) %></p>
        <% end%>
        <%= if get_flash(@conn, :error) do %>
          <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
        <% end%>

        <main role="main">
          <%= render @view_module, @view_template, assigns %>
        </main>
      </div>
    </section>

    <section class="section section-dark-blue">
      <div class="container">
          <h3>Estimator</h3>
          <p>alpha</p>
      </div>
    </section>

    <script src="<%= static_path(@conn, "/js/vendor.js") %>"></script>
    <%= if @current_user do %>
        <script>
          const testUsers = {
            'adrian': {
                name: 'Adrian Philipp',
                avatar: 'https://avatars1.githubusercontent.com/u/133832?v=3',
            },
            'kermit': {
                name: 'Kermit the Frog',
                avatar: 'https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/00/004a15610ab5d48e91edfa63e227bf1533feb2d4_full.jpg',
            },
            'kitty': {
                name: 'Kitty',
                avatar: 'https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/00/004a4566c414858db6fd5db7ee1a9144203e2060_full.jpg',
            },
            'bean': {
                name: 'Mr. Bean',
                avatar: 'https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/00/004a29db404439f047138d5914e97bd13d3574cf_full.jpg',
            },
          };

          if (window.location.search) {
              const id = window.location.search.replace('?', '');
              window.current_user = {
                  id: id,
                  name: testUsers[id].name,
                  avatar: testUsers[id].avatar,
                  device: "<%= Browser.platform(@conn) %> <%= Browser.name(@conn) %> ",
              };
          } else {
              window.current_user = {
                  id: "<%= @current_user.id %>" + window.location.search,
                  name: "<%= @current_user.name %>",
                  avatar: "<%= @current_user.avatar %>",
                  device: "<%= Browser.platform(@conn) %> <%= Browser.name(@conn) %> ",
              };
          }

          window.board_id = "<%= @board_id %>";
        </script>
    <% end %>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/estimator/web/templates/page/backlog.html.eex
<%= partial "sub_navigation.html", conn: @conn, board_id: @board_id, active: :backlog %>

<div class="card">
    <%= form_for @changeset, page_path(@conn, :select_issues, @board_id), fn form -> %>
        <div class="header">
            <h4 class="title">JIRA Backlog</h4>
            <p class="category">Please select which stories to estimate</p>
        </div>
        <div class="content">
            <%= link "Refresh", to: page_path(@conn, :backlog_refresh, @board_id), class: "btn btn-success pull-right" %>
            <%= submit "Select issues", class: "btn btn-fill btn-success backlog-submit" %>
        </div>
        <div class="content table-responsive table-full-width">
            <table class="table table-hover backlog-table">
                <thead>
                    <tr>
                      <td></td>
                      <td>Key</td>
                      <td>Summary</td>
                      <td>Estimation</td>
                    </tr>
                </thead>
                <tbody>
                <%= for issue <- @backlog["issues"] do %>
                    <tr class="<%= if issue["fields"]["flagged"] do "flagged" end %>">
                      <td width="30">
                          <%= checkbox(form, String.to_atom(issue["key"]), class: "backlog-check") %>
                      </td>
                      <td width="140">
                          <%= partial "issue_link.html", issue: issue %>
                      </td>
                      <td><%= issue["fields"]["summary"] %></td>
                      <td>
                          <%= estimation_to_card(issue["fields"][estimation_field()]) %>
                          <%= if issue["fields"]["flagged"] do %>
                            <img src="https://d1ixbz5qgnvms3.cloudfront.net/ticketswap.atlassian.net/s/-l3ljbd/b/c/1000.534.0/_/download/resources/com.pyxis.greenhopper.jira:gh-cards/images/cards/flagged.svg" />
                          <% end %>
                      </td>
                    </tr>
                <% end %>
                </tbody>
            </table>
        </div>
        <div class="content">
            <%= submit "Select issues", class: "btn btn-fill btn-success backlog-submit" %>
        </div>
    <% end %>
</div>

lib/estimator/web/templates/page/estimate.html.eex
<%= partial "sub_navigation.html", conn: @conn, board_id: @board_id, active: :estimate %>

<div>
  <div class="row">
    <div class="col-md-8">
      <div id="card-deck" class="card-container"></div>

      <div id="issue" class="card"></div>
    </div>

    <div class="col-md-4">
      <%= partial "players.html", assigns %>
    </div>
  </div>
</div>

<div class="card">
  <div class="header">
    <%= link "Deselect all", to: page_path(@conn, :deselect_all_issues, @board_id), class: "btn btn-success pull-right" %>
    <h4 class="title">All Issues to Estimate</h4>
    <p class="category">Overview over all issues to estimate. Estimated issues stay until tomorrow.</p>
  </div>
  <div class="content table-responsive table-full-width">
    <script>
      window.issues = {};
    </script>
    <%= form_for @changeset, page_path(@conn, :select_issues, @board_id), fn form -> %>
        <table class="table table-hover estimate-table">
          <thead>
          <tr>
            <td>Key</td>
            <td>Summary</td>
            <td>Estimation</td>
          </tr>
          </thead>
          <tbody>
              <%= if Enum.empty?(@selected_issues) do %>
              <tr>
                <td colspan="3">No issues yet, <%= link 'check the backlog', to: page_path(@conn, :backlog, @board_id) %>.</td>
              </tr>
              <% end %>
              <%= for issue <- @selected_issues do %>
                  <tr>
                    <td width="140"><%= partial "issue_link.html", issue: issue %></td>
                    <td>
                        <%= issue.summary %>
                        <%= radio_button(form, :current_issue_key, issue.key, style: "display:none") %>
                        <script>window.issues['<%= issue.key %>'] = <%= raw(issue_json(issue)) %></script>
                    </td>
                    <td class="estimate-<%= issue.key %>">
                        <%= issue.estimation %>
                        <%= link "deselect",
                            to: page_path(@conn, :deselect_issue, @board_id, issue.key),
                            class: "btn btn-sm btn-success btn-deselect" %>
                    </td>
                  </tr>
              <% end %>
          </tbody>
        </table>
      <% end %>
  </div>
</div>

lib/estimator/web/templates/page/estimated.html.eex
<%= partial "sub_navigation.html", conn: @conn, board_id: @board_id, active: :estimated %>

<div class="card">
  <div class="header">
    <h4 class="title">Estimated Issues</h4>
    <p class="category">Overview over all estimated stories</p>
  </div>
  <div class="content table-responsive table-full-width">
    <table class="table table-hover estimate-table">
      <thead>
      <tr>
        <td>Key</td>
        <td>Summary</td>
        <td>Estimation</td>
      </tr>
      </thead>
      <tbody>
          <%= if Enum.empty?(@issues) do %>
              <tr>
                <td colspan="3">No issues yet, <%= link 'lets estimate', to: page_path(@conn, :estimate, @board_id) %>.</td>
              </tr>
          <% end %>
          <%= for issue <- @issues do %>
              <tr>
                <td width="140">
                    <%= partial "issue_link.html", issue: issue %>
                </td>
                <td><%= issue.summary %></td>
                <td><%= issue.estimation %></td>
              </tr>
          <% end %>
      </tbody>
    </table>
  </div>
</div>

lib/estimator/web/templates/page/login.html.eex
<div class="card">
    <div class="header">
        <h4 class="title">Login</h4>
    </div>
    <div class="content">
        <p>Please login at the top right</p>
    </div>
</div>

lib/estimator/web/templates/partial/issue_link.html.eex
<a href="<%= jira_link(@issue) %>"
   class="jira-link"
   target="_blank">
    <img
        class="avatar avatar-sm"
        width="16"
        height="16"
        title="<%= @issue["fields"]["reporter"]["displayName"] %>"
        src="<%= @issue["fields"]["reporter"]["avatarUrls"]["48x48"] %>"
    />
    <img src="<%= @issue["fields"]["issuetype"]["iconUrl"] %>" title="<%= @issue["fields"]["issuetype"]["name"] %>" />
    <%= @issue["key"] %>
</a>

lib/estimator/web/templates/partial/navigation.html.eex
<div id="navigation">
    <nav class="navbar navbar-ct-transparent" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-left">
          <a class="navbar-brand" href="#">Estimator</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= if @current_user do %>
            <!--<img src="<%= @current_user.avatar %>" width="30" class="img-circle img-no-padding img-responsive"/>-->
            <%= button "Logout", to: auth_path(@conn, :delete), method: :delete, class: "btn btn-fill btn-neutral" %>
            <% else %>
            <a href="/auth/github" class="btn btn-fill btn-neutral">
              <i class="fa fa-github"></i>Login
            </a>
            <% end %>
          </li>
        </ul>
      </div><!-- /.container-->
    </nav>
</div>

lib/estimator/web/templates/partial/players.html.eex
<div class="card">
    <div class="header">
        <h4 class="title">Team Members</h4>
    </div>
    <div class="content">
        <ul id="player-list" class="list-unstyled team-members"></ul>
        <div class="footer">
            <hr>
            <div class="stats" id="estimation">
                <!--<i class="ti-timer"></i> -->
            </div>
        </div>
    </div>
</div>

lib/estimator/web/templates/partial/sub_navigation.html.eex
<div class="nav-tabs-navigation">
  <div class="nav-tabs-wrapper">
    <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
      <li class="<%= if @active == :backlog, do: "active" %>"><a href="<%= page_path(@conn, :backlog, @board_id) %>" aria-expanded="false">Backlog</a></li>
      <li class="<%= if @active == :estimate, do: "active" %>"><a href="<%= page_path(@conn, :estimate, @board_id) %>" aria-expanded="true">Estimate</a></li>
      <li class="<%= if @active == :estimated, do: "active" %>"><a href="<%= page_path(@conn, :estimated, @board_id) %>" aria-expanded="false">Stories</a></li>
    </ul>
  </div>
</div>